import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ko" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <header></header>
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        <footer></footer>
      </body>
      </html>
  );
}
